// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Resident struct {
	Nic       string `json:"nic"`
	Fullname  string `json:"fullname"`
	Raddress  string `json:"raddress"`
	Clearance string `json:"clearance"`
}
