name: Trigger auto deployment for police-check-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  release:
    types: [published]

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gramacheckservices.azurecr.io
          username: ${{ secrets.POLICECHECKTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.POLICECHECKTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gramacheckservices.azurecr.io/gramacheck/police-check-test:${{ github.event.release.tag_name }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POLICECHECKTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n police-check-test -g asgardeo-intern-project --server gramacheckservices.azurecr.io --username  ${{ secrets.POLICECHECKTEST_REGISTRY_USERNAME }} --password ${{ secrets.POLICECHECKTEST_REGISTRY_PASSWORD }}
            num=${{ github.event.release.tag_name }}
            suffix=$(echo $num | sed 's/\./\-/g')
            az containerapp update -n police-check -g asgardeo-intern-project --revision-suffix $suffix --image gramacheckservices.azurecr.io/gramacheck/police-check-test:${{ github.sha }}
